#!/bin/bash

# Log all output
exec > >(tee /var/log/userdata.log)
exec 2>&1

echo "=== Iniciando instalação do PostgreSQL ==="

# Atualizar sistema
sudo apt update -y
sudo apt install -y postgresql postgresql-contrib

echo "=== Configurando PostgreSQL ==="

# Habilitar e iniciar PostgreSQL
sudo systemctl enable postgresql
sudo systemctl start postgresql


# Reiniciar PostgreSQL
sudo systemctl restart postgresql

echo "=== Criando banco, usuário e senha ==="

sudo -u postgres psql -c "CREATE USER petuser WITH PASSWORD 'petpass';" || true
sudo -u postgres psql -c "CREATE DATABASE petcolumbia;"

cat << 'EOF' > /tmp/petcolumbia.sql

--------------------------------------------------------------
-- TABELAS
--------------------------------------------------------------

CREATE TABLE IF NOT EXISTS owner (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep             VARCHAR(255),
    complement      VARCHAR(255),
    cpf             VARCHAR(255),
    created_at      TIMESTAMP,
    email           VARCHAR(255),
    is_adm          BOOLEAN,
    last_update     TIMESTAMP,
    name            VARCHAR(255),
    neighborhood    VARCHAR(255),
    number          VARCHAR(255),
    password        VARCHAR(255),
    phone_number    VARCHAR(255),
    street          VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS employee (
    id      INT PRIMARY KEY,
    name    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS pet (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age         INT,
    breed       VARCHAR(255),
    coat        VARCHAR(255),
    created_at  TIMESTAMP,
    last_update TIMESTAMP,
    name        VARCHAR(255),
    sex         VARCHAR(255),
    size        VARCHAR(255),
    species     VARCHAR(255),
    owner_id    INT,
    CONSTRAINT fk_pet_owner
    FOREIGN KEY (owner_id) REFERENCES owner(id)
);

CREATE TABLE IF NOT EXISTS pet_offering (
    id          INT PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS pet_offering_price_and_duration (
    id              INT PRIMARY KEY,
    duration        INT,
    pet_coat        VARCHAR(255),
    pet_size        VARCHAR(255),
    price           DOUBLE PRECISION,
    pet_offering_id INT,
    CONSTRAINT fk_price_offering
    FOREIGN KEY (pet_offering_id) REFERENCES pet_offering(id)
);

CREATE TABLE IF NOT EXISTS appointment (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP,
    end_date_time   TIMESTAMP,
    is_finished     BOOLEAN,
    last_update     TIMESTAMP,
    observations    VARCHAR(255),
    pet_offerings   VARCHAR(255),
    start_date_time TIMESTAMP,
    taxi_service    BOOLEAN,
    total_price     DOUBLE PRECISION,
    employee_id     INT,
    pet_id          INT,
    CONSTRAINT fk_appointment_employee
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    CONSTRAINT fk_appointment_pet
    FOREIGN KEY (pet_id) REFERENCES pet(id)
);

CREATE TABLE IF NOT EXISTS employees_has_pet_offerings (
    employee_id      INT NOT NULL,
    pet_offering_id  INT NOT NULL,
    PRIMARY KEY (employee_id, pet_offering_id),
    CONSTRAINT fk_employee_offerings_employee
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    CONSTRAINT fk_employee_offerings_pet_offering
    FOREIGN KEY (pet_offering_id) REFERENCES pet_offering(id)
);

--------------------------------------------------------------
-- INSERTS
--------------------------------------------------------------

INSERT INTO pet_offering (id, name, description) VALUES
    (1, 'Banho completo conforme o porte e pelagem do pet', 'Banho'),
    (2, 'Tosa para manter a higiene', 'Tosa higiênica'),
    (3, 'Tosa geral', 'Tosa na máquina'),
    (4, 'Tosa bebê', 'Tosa bebê'),
    (5, 'Botinha', 'Botinha'),
    (6, 'Desembolo', 'Desembolo'),
    (7, 'Escovação dentária', 'Escovação dentária'),
    (8, 'Hidratação', 'Hidratação'),
    (9, 'Corte de unha', 'Corte de unha')
ON CONFLICT (id) DO NOTHING;

INSERT INTO employee (id, name) VALUES
    (1, 'Priscila'),
    (2, 'Rute'),
    (3, 'Keila'),
    (4, 'Taina')
ON CONFLICT (id) DO NOTHING;

INSERT INTO employees_has_pet_offerings (employee_id, pet_offering_id) VALUES
    (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9),
    (2, 1), (2, 2), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9),
    (3, 1), (3, 2), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9),
    (4, 1), (4, 2), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (1, 1, 'pp', 'curta', 55.0, 30),
    (2, 1, 'p', 'curta', 60.0, 40),
    (3, 1, 'm', 'curta', 70.0, 50),
    (4, 1, 'g', 'curta', 100.0, 78),
    (5, 1, 'gg', 'curta', 140.0, 138),
    (6, 1, 'pp', 'longa', 60.0, 30),
    (7, 1, 'p', 'longa', 70.0, 40),
    (8, 1, 'm', 'longa', 80.0, 60),
    (9, 1, 'g', 'longa', 140.0, 120),
    (10, 1, 'gg', 'longa', 140.0, 120);

INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (11, 2, 'pp', 'curta', 10.0, 10),
    (12, 2, 'p', 'curta', 10.0, 10),
    (13, 2, 'm', 'curta', 15.0, 10),
    (14, 2, 'g', 'curta', 20.0, 20),
    (15, 2, 'gg', 'curta', 20.0, 20),
    (16, 2, 'pp', 'longa', 10.0, 10),
    (17, 2, 'p', 'longa', 10.0, 10),
    (18, 2, 'm', 'longa', 15.0, 10),
    (19, 2, 'g', 'longa', 20.0, 20),
    (20, 2, 'gg', 'longa', 20.0, 20);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (21, 3, 'pp', 'curta', 35.0, 60),
    (22, 3, 'p', 'curta', 35.0, 60),
    (23, 3, 'm', 'curta', 50.0, 70),
    (24, 3, 'g', 'curta', 50.0, 42),
    (25, 3, 'gg', 'curta', 50.0, 42),
    (26, 3, 'pp', 'longa', 35.0, 60),
    (27, 3, 'p', 'longa', 35.0, 60),
    (28, 3, 'm', 'longa', 50.0, 70),
    (29, 3, 'g', 'longa', 50.0, 42),
    (30, 3, 'gg', 'longa', 50.0, 42);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (31, 4, 'pp', 'curta', 40.0, 40),
    (32, 4, 'p', 'curta', 40.0, 50),
    (33, 4, 'm', 'curta', 40.0, 70),
    (34, 4, 'g', 'curta', 60.0, 42),
    (35, 4, 'gg', 'curta', 60.0, 42),
    (36, 4, 'pp', 'longa', 40.0, 40),
    (37, 4, 'p', 'longa', 40.0, 50),
    (38, 4, 'm', 'longa', 40.0, 70),
    (39, 4, 'g', 'longa', 60.0, 42),
    (40, 4, 'gg', 'longa', 60.0, 42);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (41, 5, 'pp', 'curta', 20.0, 20),
    (42, 5, 'p', 'curta', 20.0, 20),
    (43, 5, 'm', 'curta', 20.0, 20),
    (44, 5, 'g', 'curta', 20.0, 20),
    (45, 5, 'gg', 'curta', 20.0, 20),
    (46, 5, 'pp', 'longa', 20.0, 20),
    (47, 5, 'p', 'longa', 20.0, 20),
    (48, 5, 'm', 'longa', 20.0, 20),
    (49, 5, 'g', 'longa', 20.0, 20),
    (50, 5, 'gg', 'longa', 20.0, 20);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (51, 6, 'pp', 'curta', 30.0, 30),
    (52, 6, 'p', 'curta', 30.0, 30),
    (53, 6, 'm', 'curta', 30.0, 30),
    (54, 6, 'g', 'curta', 30.0, 30),
    (55, 6, 'gg', 'curta', 30.0, 30),
    (56, 6, 'pp', 'longa', 30.0, 30),
    (57, 6, 'p', 'longa', 30.0, 30),
    (58, 6, 'm', 'longa', 30.0, 30),
    (59, 6, 'g', 'longa', 30.0, 30),
    (60, 6, 'gg', 'longa', 30.0, 30);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (61, 7, 'pp', 'curta', 5.0, 5),
    (62, 7, 'p', 'curta', 5.0, 5),
    (63, 7, 'm', 'curta', 5.0, 5),
    (64, 7, 'g', 'curta', 5.0, 5),
    (65, 7, 'gg', 'curta', 5.0, 5),
    (66, 7, 'pp', 'longa', 5.0, 5),
    (67, 7, 'p', 'longa', 5.0, 5),
    (68, 7, 'm', 'longa', 5.0, 5),
    (69, 7, 'g', 'longa', 5.0, 5),
    (70, 7, 'gg', 'longa', 5.0, 5);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (71, 8, 'pp', 'curta', 20.0, 5),
    (72, 8, 'p', 'curta', 20.0, 5),
    (73, 8, 'm', 'curta', 20.0, 5),
    (74, 8, 'g', 'curta', 20.0, 5),
    (75, 8, 'gg', 'curta', 20.0, 5),
    (76, 8, 'pp', 'longa', 30.0, 10),
    (77, 8, 'p', 'longa', 30.0, 10),
    (78, 8, 'm', 'longa', 30.0, 10),
    (79, 8, 'g', 'longa', 30.0, 10),
    (80, 8, 'gg', 'longa', 30.0, 10);


INSERT INTO pet_offering_price_and_duration (id, pet_offering_id, pet_size, pet_coat, price, duration) VALUES
    (81, 9, 'pp', 'curta', 20.0, 10),
    (82, 9, 'p', 'curta', 20.0, 10),
    (83, 9, 'm', 'curta', 20.0, 10),
    (84, 9, 'g', 'curta', 20.0, 10),
    (85, 9, 'gg', 'curta', 20.0, 10),
    (86, 9, 'pp', 'longa', 20.0, 10),
    (87, 9, 'p', 'longa', 20.0, 10),
    (88, 9, 'm', 'longa', 20.0, 10),
    (89, 9, 'g', 'longa', 20.0, 10),
    (90, 9, 'gg', 'longa', 20.0, 10);

    INSERT INTO owner (
    id, cep, complement, cpf, created_at, email, is_adm, last_update,
    name, neighborhood, number, password, phone_number, street
) VALUES
      (1, '01234567', 'Apto 101', '12345678901', NOW(), 'admin@petcolumbia.com', true, NOW(),
       'Administrador Sistema', 'Centro', '123', '$2a$10$6DNYINTrKZPcxhmMR2fxyOoBcAKQEu8TZz.cbbU0RYmSrAiNZ9/t.',
       '11987654321', 'Rua Principal'),

      (2, '12345678', 'Casa', '98765432100', NOW(), 'joao.silva@email.com', false, NOW(),
       'João Silva', 'Jardim das Flores', '456', '$2a$10$6DNYINTrKZPcxhmMR2fxyOoBcAKQEu8TZz.cbbU0RYmSrAiNZ9/t.',
       '11998765432', 'Avenida Brasil'),

      (3, '87654321', 'Apto 202', '45678912300', NOW(), 'maria.santos@email.com', false, NOW(),
       'Maria Santos', 'Vila Nova', '789', '$2a$10$6DNYINTrKZPcxhmMR2fxyOoBcAKQEu8TZz.cbbU0RYmSrAiNZ9/t.',
       '11912345678', 'Rua das Palmeiras'),

      (4, '11223344', 'Casa 2', '11122233344', NOW(), 'carlos.oliveira@email.com', false, NOW(),
       'Carlos Oliveira', 'Bairro Alto', '321', '$2a$10$6DNYINTrKZPcxhmMR2fxyOoBcAKQEu8TZz.cbbU0RYmSrAiNZ9/t.',
       '11955566677', 'Rua do Sol'),

      (5, '55667788', 'Apto 303', '99988877766', NOW(), 'ana.costa@email.com', false, NOW(),
       'Ana Costa', 'Centro Histórico', '654', '$2a$10$6DNYINTrKZPcxhmMR2fxyOoBcAKQEu8TZz.cbbU0RYmSrAiNZ9/t.',
       '11944455566', 'Avenida Central');

INSERT INTO pet (
    id, age, breed, coat, created_at, last_update,
    name, sex, size, species, owner_id
) VALUES
      (1, 3, 'Labrador', 'curta', NOW(), NOW(),
       'Thor', 'macho', 'g', 'cachorro', 2),

      (2, 2, 'Poodle', 'longa', NOW(), NOW(),
       'Mel', 'fêmea', 'p', 'cachorro', 2),

      (3, 1, 'Persa', 'longa', NOW(), NOW(),
       'Luna', 'fêmea', 'p', 'gato', 3),

      (4, 5, 'Golden Retriever', 'longa', NOW(), NOW(),
       'Max', 'macho', 'g', 'cachorro', 3),

      (5, 2, 'Bulldog Francês', 'curta', NOW(), NOW(),
       'Bob', 'macho', 'm', 'cachorro', 4),

      (6, 1, 'Shih Tzu', 'longa', NOW(), NOW(),
       'Princesa', 'fêmea', 'pp', 'cachorro', 4),

      (7, 4, 'Vira-lata', 'curta', NOW(), NOW(),
       'Toby', 'macho', 'm', 'cachorro', 5),

      (8, 3, 'Siamês', 'curta', NOW(), NOW(),
       'Miau', 'macho', 'p', 'gato', 5);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
      (1, '2025-01-01 08:00:00', '2025-01-01 09:30:00', true, '2025-01-01 08:00:00', 'Pet comportado',
       'Banho, Corte de unha', '2025-01-01 09:00:00', false, 120.0, 1, 1),

      (2, '2025-01-01 10:00:00', '2025-01-01 11:10:00', true, '2025-01-01 10:00:00', null,
       'Banho, Tosa higiênica', '2025-01-01 10:30:00', false, 80.0, 2, 2),

      (3, '2025-01-05 09:00:00', '2025-01-05 10:05:00', true, '2025-01-05 09:00:00', 'Primeira vez no petshop',
       'Banho, Escovação dentária', '2025-01-05 09:30:00', false, 75.0, 3, 3);




INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
      (4, NOW(), (CURRENT_DATE + INTERVAL '9 HOUR') + INTERVAL '1 HOUR', false, NOW(), 'Cliente VIP',
       'Banho, Tosa na máquina, Corte de unha', CURRENT_DATE + INTERVAL '9 HOUR', false, 140.0, 1, 1),

      (5, NOW(), (CURRENT_DATE + INTERVAL '14 HOUR') + INTERVAL '50 MINUTE', false, NOW(), null,
       'Banho, Hidratação', CURRENT_DATE + INTERVAL '14 HOUR', false, 90.0, 2, 2);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (6, NOW() - INTERVAL '1 DAY', ((CURRENT_DATE - INTERVAL '1 DAY') + INTERVAL '10 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '1 DAY', 'Pet muito peludo',
 'Banho, Desembolo', (CURRENT_DATE - INTERVAL '1 DAY') + INTERVAL '10 HOUR', true, 120.0, 3, 3),

(7, NOW() - INTERVAL '1 DAY', ((CURRENT_DATE - INTERVAL '1 DAY') + INTERVAL '15 HOUR') + INTERVAL '120 MINUTE', true, NOW() - INTERVAL '1 DAY', 'Banho relaxante',
 'Banho, Hidratação, Escovação dentária', (CURRENT_DATE - INTERVAL '1 DAY') + INTERVAL '15 HOUR', false, 165.0, 4, 4),

(8, NOW() - INTERVAL '1 DAY', ((CURRENT_DATE - INTERVAL '1 DAY') + INTERVAL '11 HOUR') + INTERVAL '60 MINUTE', true, NOW() - INTERVAL '1 DAY', null,
 'Tosa higiênica, Botinha, Corte de unha', (CURRENT_DATE - INTERVAL '1 DAY') + INTERVAL '11 HOUR', false, 55.0, 1, 5);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (9, NOW() - INTERVAL '2 DAY', ((CURRENT_DATE - INTERVAL '2 DAY') + INTERVAL '9 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '2 DAY', 'Muito dengosa',
 'Banho, Tosa bebê', (CURRENT_DATE - INTERVAL '2 DAY') + INTERVAL '9 HOUR', false, 100.0, 2, 6),

(10, NOW() - INTERVAL '2 DAY', ((CURRENT_DATE - INTERVAL '2 DAY') + INTERVAL '16 HOUR') + INTERVAL '50 MINUTE', true, NOW() - INTERVAL '2 DAY', null,
 'Banho, Corte de unha', (CURRENT_DATE - INTERVAL '2 DAY') + INTERVAL '16 HOUR', false, 90.0, 3, 7);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (11, NOW() - INTERVAL '3 DAY', ((CURRENT_DATE - INTERVAL '3 DAY') + INTERVAL '10 HOUR') + INTERVAL '45 MINUTE', true, NOW() - INTERVAL '3 DAY', 'Pet agitado',
 'Banho, Tosa higiênica, Escovação dentária', (CURRENT_DATE - INTERVAL '3 DAY') + INTERVAL '10 HOUR', false, 80.0, 4, 8),

(12, NOW() - INTERVAL '3 DAY', ((CURRENT_DATE - INTERVAL '3 DAY') + INTERVAL '14 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '3 DAY', 'Primeira tosa',
 'Banho, Tosa na máquina', (CURRENT_DATE - INTERVAL '3 DAY') + INTERVAL '14 HOUR', false, 110.0, 1, 1),

(13, NOW() - INTERVAL '3 DAY', ((CURRENT_DATE - INTERVAL '3 DAY') + INTERVAL '11 HOUR') + INTERVAL '50 MINUTE', true, NOW() - INTERVAL '3 DAY', null,
 'Banho, Hidratação, Corte de unha', (CURRENT_DATE - INTERVAL '3 DAY') + INTERVAL '11 HOUR', true, 110.0, 2, 2);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (14, NOW() - INTERVAL '4 DAY', ((CURRENT_DATE - INTERVAL '4 DAY') + INTERVAL '9 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '4 DAY', 'Gatinha tranquila',
 'Banho, Escovação dentária, Corte de unha', (CURRENT_DATE - INTERVAL '4 DAY') + INTERVAL '9 HOUR', false, 95.0, 3, 3),

(15, NOW() - INTERVAL '4 DAY', ((CURRENT_DATE - INTERVAL '4 DAY') + INTERVAL '15 HOUR') + INTERVAL '120 MINUTE', true, NOW() - INTERVAL '4 DAY', 'Banho completo',
 'Banho, Desembolo, Hidratação', (CURRENT_DATE - INTERVAL '4 DAY') + INTERVAL '15 HOUR', false, 190.0, 4, 4);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (16, NOW() - INTERVAL '5 DAY', ((CURRENT_DATE - INTERVAL '5 DAY') + INTERVAL '10 HOUR') + INTERVAL '60 MINUTE', true, NOW() - INTERVAL '5 DAY', 'Pet alegre',
 'Banho, Tosa higiênica, Botinha', (CURRENT_DATE - INTERVAL '5 DAY') + INTERVAL '10 HOUR', false, 85.0, 1, 5),

(17, NOW() - INTERVAL '5 DAY', ((CURRENT_DATE - INTERVAL '5 DAY') + INTERVAL '14 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '5 DAY', 'Tosa estilo bebê',
 'Banho, Tosa bebê, Corte de unha', (CURRENT_DATE - INTERVAL '5 DAY') + INTERVAL '14 HOUR', false, 120.0, 2, 6),

(18, NOW() - INTERVAL '5 DAY', ((CURRENT_DATE - INTERVAL '5 DAY') + INTERVAL '16 HOUR') + INTERVAL '50 MINUTE', true, NOW() - INTERVAL '5 DAY', null,
 'Banho, Escovação dentária', (CURRENT_DATE - INTERVAL '5 DAY') + INTERVAL '16 HOUR', false, 75.0, 3, 7);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (19, NOW() - INTERVAL '6 DAY', ((CURRENT_DATE - INTERVAL '6 DAY') + INTERVAL '9 HOUR') + INTERVAL '45 MINUTE', true, NOW() - INTERVAL '6 DAY', 'Gato manhoso',
 'Banho, Corte de unha', (CURRENT_DATE - INTERVAL '6 DAY') + INTERVAL '9 HOUR', false, 70.0, 4, 8),

(20, NOW() - INTERVAL '6 DAY', ((CURRENT_DATE - INTERVAL '6 DAY') + INTERVAL '11 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '6 DAY', 'Banho express',
 'Banho, Tosa higiênica', (CURRENT_DATE - INTERVAL '6 DAY') + INTERVAL '11 HOUR', false, 120.0, 1, 1),

(21, NOW() - INTERVAL '6 DAY', ((CURRENT_DATE - INTERVAL '6 DAY') + INTERVAL '15 HOUR') + INTERVAL '50 MINUTE', true, NOW() - INTERVAL '6 DAY', 'Cliente frequente',
 'Banho, Hidratação, Corte de unha', (CURRENT_DATE - INTERVAL '6 DAY') + INTERVAL '15 HOUR', true, 110.0, 2, 2);


INSERT INTO appointment (
    id, created_at, end_date_time, is_finished, last_update, observations,
    pet_offerings, start_date_time, taxi_service, total_price, employee_id, pet_id
) VALUES
    (22, NOW() - INTERVAL '7 DAY', ((CURRENT_DATE - INTERVAL '7 DAY') + INTERVAL '10 HOUR') + INTERVAL '1 HOUR', true, NOW() - INTERVAL '7 DAY', 'Pet muito fofo',
 'Banho, Tosa bebê, Hidratação', (CURRENT_DATE - INTERVAL '7 DAY') + INTERVAL '10 HOUR', false, 120.0, 3, 3),

(23, NOW() - INTERVAL '7 DAY', ((CURRENT_DATE - INTERVAL '7 DAY') + INTERVAL '14 HOUR') + INTERVAL '120 MINUTE', true, NOW() - INTERVAL '7 DAY', 'Cachorro grande',
 'Banho, Desembolo, Tosa higiênica', (CURRENT_DATE - INTERVAL '7 DAY') + INTERVAL '14 HOUR', false, 170.0, 4, 4),

(24, NOW() - INTERVAL '7 DAY', ((CURRENT_DATE - INTERVAL '7 DAY') + INTERVAL '16 HOUR') + INTERVAL '60 MINUTE', true, NOW() - INTERVAL '7 DAY', null,
 'Banho, Tosa na máquina, Corte de unha', (CURRENT_DATE - INTERVAL '7 DAY') + INTERVAL '16 HOUR', false, 105.0, 1, 5);


SELECT setval(pg_get_serial_sequence('owner', 'id'),       5, true);
SELECT setval(pg_get_serial_sequence('pet', 'id'),         8, true);
SELECT setval(pg_get_serial_sequence('appointment', 'id'), 24, true);

EOF

sudo -u postgres psql -d petcolumbia -f /tmp/petcolumbia.sql

echo "### BANCO PETCOLUMBIA PRONTO ###"















#!/bin/bash

# Logging
exec > >(tee /var/log/userdata.log)
exec 2>&1

echo "Starting PostgreSQL database installation..."

# Setup SSH key for accessing database instance
mkdir -p ~/.ssh
chmod 700 ~/.ssh

# Add SSH public key to authorized_keys if provided
if [ -n "${ssh_public_key}" ]; then
  echo "Setting up SSH public key..."
  touch ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
  echo "${ssh_public_key}" >> ~/.ssh/authorized_keys
fi

echo "Updating system and installing PostgreSQL..."
sudo apt update -y
sudo DEBIAN_FRONTEND=noninteractive apt install -y postgresql postgresql-contrib

echo "Configuring PostgreSQL..."
sudo systemctl enable postgresql
sudo systemctl start postgresql

# create DB and user
sudo -u postgres psql -c "CREATE USER ${db_user} WITH PASSWORD '${db_pass}';" || true
sudo -u postgres psql -c "CREATE DATABASE ${db_name} OWNER ${db_user};" || true

# listen on all interfaces (private VPC)
PG_CONF=$(sudo ls /etc/postgresql/*/main/postgresql.conf | head -n1)
PG_HBA=$(sudo ls /etc/postgresql/*/main/pg_hba.conf | head -n1)
sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" "$PG_CONF"
echo "host    all             all             10.0.0.0/24            md5" | sudo tee -a "$PG_HBA"
sudo systemctl restart postgresql
